## Real Estate Price Predictor

In [1]:
import pandas as pd
import numpy as np

In [2]:
#data frame name housing
housing=pd.read_csv("data.csv")
housing.head()

CRIM   ZN  INDUS  CHAS    NOX     RA   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.02731  0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
1  0.02729  0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
2  0.03237  0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
3  0.06905  0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   
4  0.02985  0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   9.14  21.6  
1  392.83   4.03  34.7  
2  394.63   2.94  33.4  
3  396.90   5.33  36.2  
4  394.12   5.21  28.7

In [3]:
housing.info()
#help in checking missing data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RA       501 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [4]:
housing["CHAS"].value_counts()
#0 in how many entries and 1 in how many entries

CHAS
0    471
1     35
Name: count, dtype: int64

In [5]:
housing.describe()
#from count we know the number of row shaving null values

CRIM          ZN       INDUS        CHAS         NOX          RA  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.281531   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.701426   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.209000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.619000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [6]:
housing.tail()

CRIM    ZN  INDUS  CHAS    NOX     RA   AGE     DIS  RAD  TAX  \
501  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
502  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
503  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
504  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   
505  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   

     PTRATIO       B  LSTAT  MEDV  
501     21.0  396.90   9.08  20.6  
502     21.0  396.90   5.64  23.9  
503     21.0  393.45   6.48  22.0  
504     21.0  396.90   7.88  11.9  
505     15.3  396.90   4.98  24.0

In [7]:
%matplotlib inline
#to visualise graph here only

In [8]:
import matplotlib.pyplot as plt

In [9]:
# housing.hist(bins=50,figsize=(20,15))
# #dont need plt.show()in jupyter

 ## Train-Test Splitting

In [10]:
# import numpy as np 

# #np.random.seed(42) means as many times u run it will remain same
# #dont use random bcz test data will showed in training data when ever executing aprogram
# #to avoid overfitting model will memorise all data
# def split_train_test(data,test_ratio):
#     np.random.seed(42)
#     shuffled=np.random.permutation(len(data))
#     test_set_size=int(len(data)*test_ratio)
#     test_indices=shuffled[:test_set_size]
#     train_indices=shuffled[test_set_size:]
#     return data.iloc[train_indices],data.iloc[test_indices]


In [11]:
# train_set,test_set=split_train_test(housing,0.2)

In [12]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(housing, test_size=0.2, random_state=42)

print(f"Rows in test set: {len(test_set)} Rows in train set: {len(train_set)}")


Rows in test set: 102 Rows in train set: 404


In [13]:
#If CHAS is an important feature if it is on equal part train and test data shouold represent total population
#so use stratified sampling
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(housing,housing["CHAS"]):
    strat_train_set=housing.loc[train_index]
    strat_test_set=housing.loc[test_index]


In [14]:
strat_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 404 entries, 254 to 215
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     404 non-null    float64
 1   ZN       404 non-null    float64
 2   INDUS    404 non-null    float64
 3   CHAS     404 non-null    int64  
 4   NOX      404 non-null    float64
 5   RA       400 non-null    float64
 6   AGE      404 non-null    float64
 7   DIS      404 non-null    float64
 8   RAD      404 non-null    int64  
 9   TAX      404 non-null    int64  
 10  PTRATIO  404 non-null    float64
 11  B        404 non-null    float64
 12  LSTAT    404 non-null    float64
 13  MEDV     404 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 47.3 KB


In [15]:
strat_test_set["CHAS"].value_counts()

CHAS
0    95
1     7
Name: count, dtype: int64

In [16]:
strat_train_set["CHAS"].value_counts()

CHAS
0    376
1     28
Name: count, dtype: int64

In [17]:
housing=strat_train_set.copy()

## Looking For Correlations

In [18]:
#inbuilt function in pandas to generate corelation matrix
corr_matrix=housing.corr()

In [19]:
#see pearson corelation matrix 1 refers to high corelation lie betn -1 to +1 seee +ve and  -ve corelation
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RA         0.656139
B          0.343121
ZN         0.329941
DIS        0.233118
CHAS       0.215449
RAD       -0.358722
AGE       -0.379218
CRIM      -0.396460
NOX       -0.421543
TAX       -0.437866
INDUS     -0.448480
PTRATIO   -0.488663
LSTAT     -0.735532
Name: MEDV, dtype: float64

In [20]:
# from pandas.plotting import scatter_matrix
# #plot only strong relation values
# attributes=["MEDV","RA","ZN","LSTAT"]
# scatter_matrix(housing[attributes],figsize=(12,8))

In [21]:
# housing.plot(kind="scatter",x="RA",y="MEDV",alpha=0.8)


In [22]:
#we can remove the outliers
housing["TAXRA"]=housing["TAX"]/housing["RA"]
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RA   AGE     DIS  RAD  TAX  \
254   0.03548  80.0   3.64     0  0.392  5.876  19.1  9.2203    1  315   
348   0.02899  40.0   1.25     0  0.429  6.939  34.5  8.7921    1  335   
476  15.02340   0.0  18.10     0  0.614  5.304  97.3  2.1007   24  666   
321   0.35114   0.0   7.38     0  0.493  6.041  49.9  4.7211    5  287   
326   0.24103   0.0   7.38     0  0.493  6.083  43.7  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV       TAXRA  
254     16.4  395.18   9.25  20.9   53.607897  
348     19.7  389.85   5.89  26.6   48.277850  
476     20.2  349.48  24.91  12.0  125.565611  
321     19.6  396.90   7.70  20.4   47.508691  
326     19.6  396.90  12.79  22.2   47.180667

In [23]:
# attributes=["MEDV","RA","ZN","LSTAT"]
# scatter_matrix(housing[attributes],figsize=(12,8))

In [24]:
# housing.plot(kind="scatter",x="TAX",y="MEDV",alpha=0.8)

In [25]:
housing=strat_train_set.drop("MEDV",axis=1)
housing_labels=strat_train_set["MEDV"].copy()

# #Taking Care Of Missing DATA

In [26]:
a=housing.dropna(subset=["RA"])
a.shape
# here housing data frame is not changed to change it pass inplace=True inside bracket

(400, 13)

In [27]:
#option2
housing.drop("RA",axis=1).shape
# there will be no RA coulmn shown but originally is not changed

(404, 12)

In [28]:
# option 3 replace with median mean or mode
median=housing["RA"].median()
housing["RA"].fillna(median)

254    5.876
348    6.939
476    5.304
321    6.041
326    6.083
       ...  
154    6.152
423    5.565
98     7.416
455    5.976
215    5.888
Name: RA, Length: 404, dtype: float64

In [29]:
housing.shape


(404, 13)

In [30]:
housing.describe()
# before starting imputer

CRIM          ZN       INDUS        CHAS         NOX          RA  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  400.000000   
mean     3.679998   10.189356   11.311510    0.069307    0.557245    6.246295   
std      8.250018   21.930822    6.817292    0.254290    0.116497    0.683783   
min      0.009060    0.000000    0.740000    0.000000    0.385000    3.561000   
25%      0.088282    0.000000    5.190000    0.000000    0.452000    5.874750   
50%      0.280140    0.000000    9.900000    0.000000    0.538000    6.175000   
75%      3.694070    3.125000   18.100000    0.000000    0.625750    6.593500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO          B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.00000   
mean    68.477723    3.779174    9.690594  411.136139   18.507178  353.51651   
std     28.458507    2.125534    8.763267  168.375404    2.120799   95.10835   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.32000   
25%     44.850000    2.070275    4.000000  283.250000   17.400000  374.23750   
50%     77.500000    3.167500    5.000000  335.000000   19.050000  390.94000   
75%     94.600000    5.104475   24.000000  666.000000   20.200000  396.15750   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.90000   

            LSTAT  
count  404.000000  
mean    12.813515  
std      7.188163  
min      1.730000  
25%      7.385000  
50%     11.490000  
75%     16.977500  
max     37.970000

In [31]:
#if test set have missing data
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy="median");
imputer.fit(housing)
# fit imputer to housing data

SimpleImputer(strategy='median')

In [32]:
imputer.statistics_
# reeplace every null value with median in every attribute

array([2.8014e-01, 0.0000e+00, 9.9000e+00, 0.0000e+00, 5.3800e-01,
       6.1750e+00, 7.7500e+01, 3.1675e+00, 5.0000e+00, 3.3500e+02,
       1.9050e+01, 3.9094e+02, 1.1490e+01])

In [33]:
X=imputer.transform(housing)

In [34]:
housing_tr=pd.DataFrame(X,columns=housing.columns)
#transformed missing value of missing data

In [35]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RA  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.679998   10.189356   11.311510    0.069307    0.557245    6.245589   
std      8.250018   21.930822    6.817292    0.254290    0.116497    0.680418   
min      0.009060    0.000000    0.740000    0.000000    0.385000    3.561000   
25%      0.088282    0.000000    5.190000    0.000000    0.452000    5.875000   
50%      0.280140    0.000000    9.900000    0.000000    0.538000    6.175000   
75%      3.694070    3.125000   18.100000    0.000000    0.625750    6.582500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO          B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.00000   
mean    68.477723    3.779174    9.690594  411.136139   18.507178  353.51651   
std     28.458507    2.125534    8.763267  168.375404    2.120799   95.10835   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.32000   
25%     44.850000    2.070275    4.000000  283.250000   17.400000  374.23750   
50%     77.500000    3.167500    5.000000  335.000000   19.050000  390.94000   
75%     94.600000    5.104475   24.000000  666.000000   20.200000  396.15750   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.90000   

            LSTAT  
count  404.000000  
mean    12.813515  
std      7.188163  
min      1.730000  
25%      7.385000  
50%     11.490000  
75%     16.977500  
max     37.970000

## SK learn Library 

In [36]:
#sk learn has 3 objects
# 1 Estimators-It estimates some parameter based on a data set like imputer
# it has a fit method and transform method
#Fit-method-Fits The Data SEt and Calculates Internal Parameter has hyper parameter like strategy
#Transform Method-Take input and returns outp
#Tra

In [37]:
# building pipeline and before it automate the data set


## Feature Scaling

In [38]:
# primarily 2 types of feature scaling Method
# 1.Min-max Scaling(Normalisation)
# (value-min)/(max-min)
# here value lie in certain range ie from 0 to 1
# Sklearn provides MinMAxScaler for this
# 2.Standardisation
#  (value-mean)/standarddeviation
#  Sklearn provides StandardScaler for this



In [39]:
from sklearn.pipeline import Pipeline
# feature scaling scale feature value to cer     
from sklearn.preprocessing import StandardScaler
# add as many things in pipeline ,pipeline takes a string
my_pipeline=Pipeline([("imputer",SimpleImputer(strategy="median")),
                     ("std_scaler",StandardScaler())])

In [40]:
housing_num_tr=my_pipeline.fit_transform(housing)
#every process u done must be in pipeline so transform before imputed data to the pipe line 

In [41]:
housing_num_tr
#it is an numpy array predictor use numpy array as input

array([[-0.44230647,  3.18716752, -1.12669699, ..., -0.99480936,
         0.4386066 , -0.49636234],
       [-0.44309412,  1.36098896, -1.47771078, ...,  0.56313712,
         0.38249576, -0.96437708],
       [ 1.37665966, -0.46518961,  0.9970099 , ...,  0.79918962,
        -0.0424938 ,  1.68492063],
       ...,
       [-0.43828696, -0.46518961, -1.23684776, ..., -0.23944137,
         0.45671366, -0.92259005],
       [ 0.12000683, -0.46518961,  0.9970099 , ...,  0.79918962,
        -3.61126915,  0.86310904],
       [-0.44107829, -0.46518961,  0.3786969 , ..., -0.99480936,
         0.41355148,  0.09701349]])

## Selecting A Desired Model

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# model=LinearRegression()
# model=DecisionTreeRegressor()
model=RandomForestRegressor()
model.fit(housing_num_tr,housing_labels)

RandomForestRegressor()

In [43]:
some_data=housing.iloc[:5]
some_labels=housing_labels.iloc[:5]
prepared_data=my_pipeline.transform(some_data)
model.predict(prepared_data)

array([20.449, 27.445, 12.958, 20.669, 21.757])

In [44]:
list(some_labels)

[20.9, 26.6, 12.0, 20.4, 22.2]

## Evaluating The Model

In [45]:
from sklearn.metrics import mean_squared_error
housing_predictions=model.predict(housing_num_tr)
mse = mean_squared_error(housing_labels,housing_predictions)
rmse = np.sqrt(mse)

In [46]:
rmse
# it has 0 errror bcz it deeply understand the model and got over fitted also learned the noise 

1.259158045152898

## Using Better Evaluation Technique And Cross Validation

In [47]:
#1 2 3 4  5  67 8 9 
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model,housing_num_tr,housing_labels,scoring="neg_mean_squared_error",cv=10)
#do or 10 folds our scores here negative
rmse_scores=np.sqrt(-scores)
rmse_scores
# for prices to have 24 32 36 etc 4 to 5 error is ok

array([3.42675745, 2.63825283, 4.89447738, 2.6488895 , 4.37081772,
       2.4794544 , 3.30712016, 3.48740023, 1.83897327, 4.3859637 ])

In [48]:
def print_scores(scores):
    print("Scores:",scores)
    print("Mean:",scores.mean())
    print("standard Deviation:", scores.std())

In [49]:
print_scores(rmse_scores)

Scores: [3.42675745 2.63825283 4.89447738 2.6488895  4.37081772 2.4794544
 3.30712016 3.48740023 1.83897327 4.3859637 ]
Mean: 3.347810662416186
standard Deviation: 0.9255513296054628


## Saving The Model

In [52]:
from joblib import dump, load
dump(model, "RealEstate.joblib")

['RealEstate.joblib']

## TESTING THE MODEL

In [55]:
X_test=strat_test_set.drop("MEDV",axis=1)
Y_test=strat_test_set["MEDV"].copy()
X_test_prepared=my_pipeline.transform(X_test)
final_predictions=model.predict(X_test_prepared)
final_mse=mean_squared_error(Y_test,final_predictions)
final_rmse=np.sqrt(final_mse)
#print(final_predictions,list(Y_test))

In [56]:
final_rmse

3.3494172349418467

In [57]:
prepared_data[0]

array([-0.44230647,  3.18716752, -1.12669699, -0.27288841, -1.42019852,
       -0.54385314, -1.7372291 ,  2.56306103, -0.99293673, -0.57167103,
       -0.99480936,  0.4386066 , -0.49636234])